server:
  port: 9999
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/books?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1qaz@WSX#EDC
    driver-class-name: com.mysql.jdbc.Driver